# Generated by Django 6.1 on 2026-10-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("imageURL", models.URLField()),
                ("price", models.CharField(max_length=255)),
                (
                    "rating",
                    models.FloatField(
                        choices=[
                            (0, "0"),
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                        ]
                    ),
                ),
            ],
        ),
    ]
