# Generated by Django 6.0.4 on 2026-04-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=100)),
                (
                    "type_of_company",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Finance", "Finance"),
                            ("Manufacturing", "Manufacturing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("about", models.TextField()),
                ("date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
    ]
